Additional content for semirings
james-d-mitchell/libsemigroups-python-bindings pull request #12
Opened 2017-07-12 16:05 UTC by aal20

Changes name of `Semiring` class to `SemiringABC`.

Adds documentation and unittests to `Integers`, `MinPlusSemiring` and `MaxPlusSemiring, and all member functions.

Removes unnecessary `__init__` methods.

Replaces static methods, with functions and decorators, to make them static
methods in line with linting.

Adds `BooleanSemiring`, together with documentation and unittests.

Adds `SemiringWithThresholdABC`, as an abstract base class.

Adds `TropicalMinPlusSemiring`, `TropicalMaxPlusSemiring` and `NaturalSemiring` classes as subclasses of `SemiringWithThresholdABC`, together with documentation and unittests.

2017-07-12 18:36 UTC, james-d-mitchell commented
Something has gone wrong, the commits by others shouldn't show up here. Make sure enough rebased against the most recent master branch

2017-07-12 21:28 UTC, aal20 commented
Sorted?

2017-07-13 09:15 UTC, aal20 commented
Fixed oxford comma and replaced bitwise operators.

2017-07-13 12:32 UTC, james-d-mitchell requested changes
This mostly looks good, some minor tweaks are required, but after that I'll merge it. One thing that might be missing is the min-plus semiring. Is this intentional?

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
> +    distributive and, multiplication by 0 must annihilate :math:`R`.
"and, " -> ", and"

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
> +        return x | y
change to `or`

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
> +        return x & y
Change to `and`

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
>          return min(x, y)
Shouldn't this be `max(x, y)`? Using `min` contradicts both the doc and the name...

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
> +            return x
Is this right? Shouldn't it return `float('inf')`, since `x` might be `0` and `y` might be infinity.

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
> +        A function to find the integer sum modulo :math:`\equiv`, of two
What is `\equiv` here? Be more specific.

2017-07-13 12:32 UTC, james-d-mitchell commented on semigroups/semiring.py
> +    Let :math:`t\in\mathbb{N}_0, p\in\mathbb{N}` and :math:`\equiv` be the
Maybe write `\mathbb{N} \cup \{0\}` to be safe.

2017-07-13 13:06 UTC, aal20 commented on semigroups/semiring.py
> +            return x
I think it should return min(x, y), as this checks if at least one of them equals infinity

2017-07-13 13:20 UTC, aal20 commented on semigroups/semiring.py
> +            return x
Sorry, was looking at the wrong line. You're right.

2017-07-13 13:23 UTC, aal20 commented on semigroups/semiring.py
> +        A function to find the integer sum modulo :math:`\equiv`, of two
Would saying the `\equiv` is the semiring's congruence relation be adequate?

2017-07-13 13:36 UTC, aal20 commented
I think `MinPlusSemiring` is there.

2017-07-13 15:33 UTC, james-d-mitchell commented on semigroups/semiring.py
> +        min plus semiring. If the integer sum is greater than :math:`t`, then
I think you should be more explicit here, since if either value is infinity, then we return infinity.

2017-07-13 15:33 UTC, james-d-mitchell commented on semigroups/semiring.py
> +            return x
It should be infinity if either x or y is infinity, and the sum otherwise

2018-05-04 10:25 UTC, merged